# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dexctl < Formula
  desc "A command line tool for Dex IdP gRPC interface"
  homepage "https://github.com/rudeigerc/dexctl"
  version "0.0.1-alpha.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rudeigerc/dexctl/releases/download/v0.0.1-alpha.1/dexctl_Darwin_x86_64"
      sha256 "42e8618dbf97abe096aec1e0e4d30e618e3dc6c8e1b378a68a54375403ceb5f7"

      def install
        bin.install "dexctl_Darwin_x86_64" => "dexctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rudeigerc/dexctl/releases/download/v0.0.1-alpha.1/dexctl_Darwin_arm64"
      sha256 "4080d33ef5551a3c68cd5c8db7785c26ea5aad51cbd8ea674cc7a09a687bd08b"

      def install
        bin.install "dexctl_Darwin_arm64" => "dexctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudeigerc/dexctl/releases/download/v0.0.1-alpha.1/dexctl_Linux_arm64"
      sha256 "13346f7c42247b89c79bebb84260be2eb6f6f9746ff4bf7285c8c23254aee8da"

      def install
        bin.install "dexctl_Linux_arm64" => "dexctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rudeigerc/dexctl/releases/download/v0.0.1-alpha.1/dexctl_Linux_x86_64"
      sha256 "2b597808007058a3b0f1c08852834a74b82c7d6f61f62504f7a379ca09b45f93"

      def install
        bin.install "dexctl_Linux_x86_64" => "dexctl"
      end
    end
  end

  test do
    system "#{bin}/dexctl version --client"
  end
end
